services:
  sz-gameshow:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - sz-gameshow-db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 80:80

  sz-gameshow-db:
      container_name: db
      platform: linux/x86_64
      image: mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: testRootPassword
          MYSQL_DATABASE: local_test
          MYSQL_USER: testUser
          MYSQL_PASSWORD: testPassword
      volumes:
          - ./php/database_raw.sql:/docker-entrypoint-initdb.d/database_raw.sql
      ports:
          - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: sz-gameshow-db
    depends_on:
        - sz-gameshow-db